### ISSUE TITLE
为什么残差模块ResidualBlock中需要加一个downsample？

### ISSUE THREAD

**Issue by zsn6034** [SherlockLiao/code-of-learn-deep-learning-with-pytorch#1]
按照代码的意思，downsample就是使x经历过1个3x3卷积再进行一次BatchNorm操作再与F(x)相加，为什么要加这一步骤，新手入门PyTorch，求大神解释下

**Comment by SherlockLiao** [comment]
不加downsample的话，网络的输入尺寸就一直保持不变，但是卷积网络需要在不断传播的过程中越来越小，这样才能到最后的全连接，所以需要加一个downsample来减半尺寸
