### ISSUE TITLE
你好，我用你的代码时，报错了，如何解决啊？

### ISSUE THREAD

**Issue by codes-kzhan** [SherlockLiao/code-of-learn-deep-learning-with-pytorch#5]
fcn语义分割的代码。
python main.py train
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    from data import VocSegDataset, img_transforms, COLORMAP

**ImportError: cannot import name 'VocSegDataset'**

**Comment by SherlockLiao** [comment]
你可以重新试试，我已经上传好了代码
